In [1]:
import numpy as np

In [2]:
mat = []

In [3]:
def findEigen(n):
    for i in range(n):
        row = []
        mat.append(row)
        for j in range(n):
            row.append(int(input(f"Enter Element {i}{j}: ")))
    print(f"The matrix is: {mat}")
    eigenvalues, eigenvectors = np.linalg.eig(mat)
    print(f"Eigenvalues: {eigenvalues}")
    print(f"Eigenvectors: {eigenvectors}")



In [4]:
np.linalg.eig?

Signature: np.linalg.eig(a)
Docstring:
Compute the eigenvalues and right eigenvectors of a square array.

Parameters
----------
a : (..., M, M) array
    Matrices for which the eigenvalues and right eigenvectors will
    be computed

Returns
-------
w : (..., M) array
    The eigenvalues, each repeated according to its multiplicity.
    The eigenvalues are not necessarily ordered. The resulting
    array will be of complex type, unless the imaginary part is
    zero in which case it will be cast to a real type. When `a`
    is real the resulting eigenvalues will be real (0 imaginary
    part) or occur in conjugate pairs

v : (..., M, M) array
    The normalized (unit "length") eigenvectors, such that the
    column ``v[:,i]`` is the eigenvector corresponding to the
    eigenvalue ``w[i]``.

Raises
------
LinAlgError
    If the eigenvalue computation does not converge.

See Also
--------
eigvals : eigenvalues of a non-symmetric array.
eigh : eigenvalues and eigenvectors of a real symmet

In [5]:
findEigen(int(input("Enter the dimension of the Square Matrix")))

The matrix is: [[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0]]
Eigenvalues: [-1.  3. -1. -1.]
Eigenvectors: [[-0.8660254   0.5        -0.16928072  0.06319169]
 [ 0.28867513  0.5         0.85717325 -0.27857451]
 [ 0.28867513  0.5        -0.34394626 -0.56134079]
 [ 0.28867513  0.5        -0.34394626  0.77672361]]


In [6]:
A = np.array([[1,2,3], [4,5,6]])

eig1, U = np.linalg.eig(A @ A.T)
eig2, V = np.linalg.eig(A.T @ A)

In [7]:
print(f"The eigen values and eigen vectors for AAt is: {eig1} \n {U}")
print(f"The eigen values and eigen vectors for AtA is: {eig2} \n {V}")

The eigen values and eigen vectors for AAt is: [ 0.59732747 90.40267253] 
 [[-0.92236578 -0.3863177 ]
 [ 0.3863177  -0.92236578]]
The eigen values and eigen vectors for AtA is: [ 9.04026725e+01  5.97327474e-01 -4.04484173e-15] 
 [[-0.42866713 -0.80596391  0.40824829]
 [-0.56630692 -0.11238241 -0.81649658]
 [-0.7039467   0.58119908  0.40824829]]


In [8]:
lambda_1 = np.diag(np.sqrt(eig1))
lambda_1

array([[0.77286964, 0.        ],
       [0.        , 9.508032  ]])

In [9]:
lamda = np.zeros_like(A)
lamda

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
lamda = np.add(lamda, lambda_1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
np.linalg.svd?

Signature: np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)
Docstring:
Singular Value Decomposition.

When `a` is a 2D array, and ``full_matrices=False``, then it is
factorized as ``u @ np.diag(s) @ vh = (u * s) @ vh``, where
`u` and the Hermitian transpose of `vh` are 2D arrays with
orthonormal columns and `s` is a 1D array of `a`'s singular
values. When `a` is higher-dimensional, SVD is applied in
stacked mode as explained below.

Parameters
----------
a : (..., M, N) array_like
    A real or complex array with ``a.ndim >= 2``.
full_matrices : bool, optional
    If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
    ``(..., N, N)``, respectively.  Otherwise, the shapes are
    ``(..., M, K)`` and ``(..., K, N)``, respectively, where
    ``K = min(M, N)``.
compute_uv : bool, optional
    Whether or not to compute `u` and `vh` in addition to `s`.  True
    by default.
hermitian : bool, optional
    If True, `a` is assumed to be Hermitian (symmetri